version: '3'

services:
  app:
    image: sohanhk07/myproject:v1
    ports:
      - "8090:8080"
    environment:
      - JAVA_MINIMAL=/opt/jre
      - PATH=$PATH:$JAVA_MINIMAL/bin
    volumes:
      - ./target/springboot-maven-course-micro-svc-0.0.1-SNAPSHOT.jar:/app.jar
